# typed: false
# frozen_string_literal: true

# This file is generated by the update-homebrew-formula command in
# https://github.com/hatayama/unity-cli-loop — do not edit by hand.
class Uloop < Formula
  desc "Let AI drive Unity, from Editor to Play Mode"
  homepage "https://github.com/hatayama/unity-cli-loop"
  version "3.1.0"
  license "MIT"

  depends_on :macos

  on_macos do
    on_arm do
      url "https://github.com/hatayama/unity-cli-loop/releases/download/dispatcher-v3.1.0/uloop-dispatcher-darwin-arm64.tar.gz"
      sha256 "ba70cfca1e1a4781ee6913d78d891d740fb5aa27a500963925fcf2b746b5097c"
    end
    on_intel do
      url "https://github.com/hatayama/unity-cli-loop/releases/download/dispatcher-v3.1.0/uloop-dispatcher-darwin-amd64.tar.gz"
      sha256 "844b4796c40d6de807b3eb82fe108e94b3fa93368025eba4c1ce220bb049901d"
    end
  end

  def install
    bin.install "uloop"
  end

  def caveats
    legacy_path = File.expand_path("~/.local/bin/uloop")
    return "" unless File.exist?(legacy_path)

    <<~EOS
      A curl-installed uloop exists at #{legacy_path}.
      Remove it (or fix your PATH order) so the Homebrew-managed
      binary is the one that runs:
        rm #{legacy_path}
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uloop --version")
  end
end
