# typed: false
# frozen_string_literal: true

# This file is generated by the update-homebrew-formula command in
# https://github.com/hatayama/unity-cli-loop — do not edit by hand.
class Uloop < Formula
  desc "Let AI drive Unity, from Editor to Play Mode"
  homepage "https://github.com/hatayama/unity-cli-loop"
  version "3.0.0-beta.33"
  license "MIT"

  depends_on :macos

  on_macos do
    on_arm do
      url "https://github.com/hatayama/unity-cli-loop/releases/download/dispatcher-v3.0.0-beta.33/uloop-dispatcher-darwin-arm64.tar.gz"
      sha256 "dfdff42d11304f0f0183fac475f99a2818dde10efc7c45b0f5530a13124c772a"
    end
    on_intel do
      url "https://github.com/hatayama/unity-cli-loop/releases/download/dispatcher-v3.0.0-beta.33/uloop-dispatcher-darwin-amd64.tar.gz"
      sha256 "cc55934ae9ed2ea39880219b87f16d2942de4eedab263b086dbe7d5a7d01448f"
    end
  end

  def install
    bin.install "uloop"
  end

  def caveats
    legacy_path = File.expand_path("~/.local/bin/uloop")
    return "" unless File.exist?(legacy_path)

    <<~EOS
      A curl-installed uloop exists at #{legacy_path}.
      Remove it (or fix your PATH order) so the Homebrew-managed
      binary is the one that runs:
        rm #{legacy_path}
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uloop --version")
  end
end
