# typed: false
# frozen_string_literal: true

# This file is generated by the update-homebrew-formula command in
# https://github.com/hatayama/unity-cli-loop — do not edit by hand.
class Uloop < Formula
  desc "Let AI drive Unity, from Editor to Play Mode"
  homepage "https://github.com/hatayama/unity-cli-loop"
  version "3.2.0"
  license "MIT"

  depends_on :macos

  on_macos do
    on_arm do
      url "https://github.com/hatayama/unity-cli-loop/releases/download/dispatcher-v3.2.0/uloop-dispatcher-darwin-arm64.tar.gz"
      sha256 "b6584314a9413386ec150662ceed1058f2311ef0ee53e5ae66fb934f2b123dd7"
    end
    on_intel do
      url "https://github.com/hatayama/unity-cli-loop/releases/download/dispatcher-v3.2.0/uloop-dispatcher-darwin-amd64.tar.gz"
      sha256 "5ce6ae28a5288d9257701807236d32709602957b43f4bd08ba802dbb10f41e6d"
    end
  end

  def install
    bin.install "uloop"
  end

  def caveats
    legacy_path = File.expand_path("~/.local/bin/uloop")
    return "" unless File.exist?(legacy_path)

    <<~EOS
      A curl-installed uloop exists at #{legacy_path}.
      Remove it (or fix your PATH order) so the Homebrew-managed
      binary is the one that runs:
        rm #{legacy_path}
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uloop --version")
  end
end
